import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
     name: "2021 Lorem 1",
     image: scooter,
     version: "VDI BS VI",
     speed: 100,
     engine_type: "Automatic",
     variant: "Electric",
     emi: 4333,
     price: 75999,
     category: "bike",
     rating: 4,
  },
  {
    _id: uuid(),
     name: "2021 Lorem 2",
     image: scooter,
     version: "VDI BS VI",
     speed: 100,
     engine_type: "semi automatic",
     variant: "Electric",
     emi: 4333,
     price: 65999,
     category: "scooter",
     rating: 1,
  },
  {
    _id: uuid(),
     name: "2021 Lorem 3",
     image: scooter,
     version: "VDI BS VI",
     speed: 100,
     engine_type: "Automatic",
     variant: "Electric",
     emi: 4333,
     price: 92199,
     category: "bike",
     rating: 2,
  },
  {
    _id: uuid(),
     name: "2021 Lorem 4",
     image: scooter,
     version: "VDI BS VI",
     speed: 100,
     engine_type: "Automatic",
     variant: "Electric",
     emi: 4333,
     price: 54999,
     category: "scooter",
     rating: 5,
  },
  {
    _id: uuid(),
     name: "2021 Lorem 5",
     image: scooter,
     version: "VDI BS VI",
     speed: 100,
     engine_type: "Automatic",
     variant: "Electric",
     emi: 4333,
     price: 58099,
     category: "scooter",
     rating: 3,
  },
  {
    _id: uuid(),
     name: "2021 Lorem 6",
     image: scooter,
     version: "VDI BS VI",
     speed: 100,
     engine_type: "Automatic",
     variant: "Electric",
     emi: 4333,
     price: 58099,
     category: "bike",
     rating: 4,
  },
  {
    _id: uuid(),
     name: "2021 Lorem 7",
     image: scooter,
     version: "VDI BS VI",
     speed: 100,
     engine_type: "Automatic",
     variant: "Electric",
     emi: 4333,
     price: 72000,
     category: "bike",
     rating: 1,
  },
  {
    _id: uuid(),
     name: "2021 Lorem 7",
     image: scooter,
     version: "VDI BS VI",
     speed: 100,
     engine_type: "Automatic",
     variant: "Electric",
     emi: 4333,
     price: 98000,
     category: "bike",
     rating: 2,
  },
  {
    _id: uuid(),
     name: "2021 Lorem 7",
     image: scooter,
     version: "VDI BS VI",
     speed: 100,
     engine_type: "Automatic",
     variant: "Electric",
     emi: 4333,
     price: 150999,
     category: "scooter",
     rating: 5,
     
  },
];
